spring:
  application:
    name: depotshop-domain

  datasource:
    url: jdbc:mariadb://localhost:3306/depot
    username: root
    password: dosel2
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
---
spring:
  config:
    activate:
      on-profile: test


  datasource:
    url: jdbc:mariadb://localhost:3306/depot
    username: root
    password: dosel2
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

