spring:
  profiles:
    group:
      local: domain, infra

  datasource:
    url: jdbc:mariadb://localhost:3306/depot
    username: root
    password: dosel2
    driver-class-name: org.mariadb.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDB106Dialect
          show-sql: true
          format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

server:
  port: 8085

---
spring:
  config:
    activate:
      on-profile: test